stages:
  - build
  - test
build:
  stage: build
  script:
    - ./Online-workshop-beatrice/gradlew build
test:
  stage: test
  script:
    - ./Online-workshop-beatrice/gradlew test
  dependencies:
    - build