stages:
  - build
  - test
  - sonarqube
build:
  stage: build
  script:
    - cd Online-workshop-beatrice/
    - ./gradlew build
test:
  stage: test
  script:
    - cd Online-workshop-beatrice/
    - ./gradlew test
  dependencies:
    - build
sonarqube:
  stage: sonarqube
  script:
    - cd Online-workshop-beatrice/
    - ./gradlew sonarqube
  dependencies:
    - test