stages:
  - build
  - test
build:
  stage: build
  script:
    - cd Online-workshop-beatrice/
    - ./gradlew build
test:
  stage: test
  script:
    - cd Online-workshop-beatrice/
    - ./gradlew test
  dependencies:
    - build