--- 
build: 
  script: 
    - "cd Online-workshop-beatrice/"
    - "./gradlew build"
  stage: build
deploy: 
  script: 
    - "cd Online-workshop-beatrice/"
    - "./gradlew shadowJar"
    - "docker build -t bforslund/ips-webshop-backend ."
    - "docker login -u $docker_username -p $docker_password"
    - "docker push bforslund/ips-webshop-backend"
    - "cd .."
    - "cd Front-end-webshop/"
    - "npm install"
    - "npm run build-prod"
    - "docker build -t bforslund/ips-webshop-frontend ."
    - "docker push bforslund/ips-webshop-frontend"
  stage: deploy
sonarqube: 
  dependencies: 
    - test
  script: 
    - "cd Online-workshop-beatrice/"
    - "./gradlew sonarqube"
  stage: sonarqube
stages: 
  - build
  - test
  - sonarqube
  - deploy
test: 
  dependencies: 
    - build
  script: 
    - "cd Online-workshop-beatrice/"
    - "./gradlew test"
  stage: test